
server:
  port: 8082

spring:
  data:
    mongodb:
      database: test
      host: localhost
      port: 27017
      threads-allowed-to-block-for-connection-multiplier: 20
      connect-timeout: 10000
      socket-timeout: 10000
      max-wait-time: 5000
      connections-per-host: 20

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB


  thymeleaf:
    mode: HTML
    cache: false

cloud:
  elasticsearch:
    host: localhost
    port: 9200
#    host: 81.69.247.172
#    port: 8888