version: '2.1'
services:
  ad-mongodb:
    image: mongo:5.0.14
    container_name: ad-mongodb
    networks:
      - custom_net
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo/configdb:/data/configdb
      - ./data/mongo/db:/data/db
      - ./data/mongo/log:/var/log/mongodb  # 挂载日志目录
    command: mongod --auth
    #初始化管理员用户名和密码
    environment:
     MONGO_INITDB_ROOT_USERNAME: admin
     MONGO_INITDB_ROOT_PASSWORD: 123456Cx
     # MONGO_INITDB_DATABASE: all-docs
    tty: true

  ad-elasticsearch:
    image: elasticsearch:7.9.3
    container_name: ad-elasticsearch
    networks:
      - custom_net
    restart: always
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data:rw
      - ./data/elasticsearch/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/elasticsearch/conf/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./data/elasticsearch/logs:/user/share/elasticsearch/logs:rw
      - ./esplugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  ad-kibana:
    image: kibana:7.9.3
    container_name: "ad-kibana"
    networks:
      - custom_net
    ports:
      - "5601:5601"
    #restart: always
    depends_on:
      - ad-elasticsearch
    volumes:
      - ./data/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

  ad-redis:
    image: redis:latest
    container_name: ad-redis
    networks:
      - custom_net
    command: redis-server /etc/redis/redis.conf
    ports:
      - 16379:6379
    volumes:
      - ./data/redis:/data
      - ./data/redis/redis.conf:/etc/redis/redis.conf

  ad-server:
    image: document:latest
    container_name: ad-server
    networks:
      - custom_net
    environment:
      - REDIS_HOST=ad-redis
      - REDIS_PORT=16379
      - REDIS_PWD=123456Cx
      - MONGO_HOST=ad-mongodb
      - MONGO_PORT=27017
      - MONGO_USER=admin
      - MONGO_PWD=123456Cx
      - ES_HOST=ad-elasticsearch
      - ES_PORT=9200
      - ES_USER=
      - ES_PWD=
    ports:
      - 8082:8082
    working_dir: /home/coostack/document/
    command: java -jar -Xms64m -Xmx64m -XX:MetaspaceSize=64m -Dspring.config.location=application.yml target/document-sharing-site-1.0-SNAPSHOT.jar
    volumes:
    #  - ../target/:/home/coostack/document/target/
    #  - ../src/config/application.xproperties:/home/coostack/document/application.xproperties
      - ../src/config/application.yml:/home/coostack/document/application.yml
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "8082"]
      interval: 6s
      timeout: 10s
      retries: 20
    depends_on:
      - ad-mongodb
      - ad-redis

  ad-web:
    image: document-web:latest
    container_name: ad-web
    networks:
      - custom_net
    ports:
      - 80:80
    depends_on:
      - ad-server

# 容器之间通讯
networks:
  custom_net:
    external:
      name: app_net











