version: '2'
services:
  mongodb:
    image: mongo
    container_name: all_docs_mongodb
    restart: always
    ports:
      - ${MONGO_PORT:27017}:27017
    volumes:
      - "./data/configdb:/data/configdb"
      - "./data/db:/data/db"
    command: mongod --auth
    #初始化管理员用户名和密码
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:""}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD:""}
    tty: true

  elasticsearch:
    image: elasticsearch:6.8.12
    container_name: all_docs_elasticsearch
    restart: always
    volumes:
      - /data/elasticsearch/data:/usr/share/elasticsearch/data:rw
      - /data/elasticsearch/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/elasticsearch/conf/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - /data/elasticsearch/logs:/user/share/elasticsearch/logs:rw
    ports:
      - ${ES_PORT_1:9200}:9200
      - ${ES_PORT_2:9300}:9300
    environment:
      - discovery.type=single-node

  redis:
    image: "redis:latest"
    container_name: all_docs_redis
    command: redis-server /etc/redis/redis.conf
    ports:
      - ${REDIS_PORT:16379}:6379"
    volumes:
      - ./data:/data
      - ./redis.conf:/etc/redis/redis.conf

  web:
    image: "all-docs-backend"
    container_name: all_docs_backend
    ports:
      - 8082:8082
    depends_on:
      - mongodb
      - redis
