
server:
  port: 8082

spring:
  data:
    mongodb:
      database: document
      host: ad-mongodb
      port: 27017
      username: admin
      password: 123456Cx
      threads-allowed-to-block-for-connection-multiplier: 20
      connect-timeout: 10000
      socket-timeout: 10000
      max-wait-time: 5000
      connections-per-host: 20

  redis:
    database: 0
    host: ad-redis
    password: 123456Cx
    port: 6379
    timeout: 3000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 50
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
    testOnBorrow: true

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB


  thymeleaf:
    mode: HTML
    cache: false

cloud:
  elasticsearch:
    host: ad-elasticsearch
    port: 9200

all-docs:
  config:
    userUpload: true
    adminReview: true
    prohibitedWord: true
    userRegistry: false
